import Joi from "joi"

export const _HOSTNAME_SCHEMA = Joi.string().hostname().required()
export const _INTEGER_SCHEMA = Joi.number().integer().min(1).required()

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "production").default("development"),
  APP_PORT: Joi.number().port().required(),
  APP_NAME: Joi.string().required(),
  APP_PREFIX: Joi.string(),
  APP_VERSION: Joi.string(),
  SWAGGER_ON: Joi.boolean().required(),
  SWAGGER_PATH: Joi.string(),
  SWAGGER_TITLE: Joi.string(),
  SWAGGER_DESCRIPTION: Joi.string(),
  SWAGGER_VERSION: Joi.string(),
  COOKIE_SECRET: Joi.string().required(),
  ASSETS_PREFIX: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRES_IN: _INTEGER_SCHEMA,
  JWT_REFRESH_EXPIRES_IN: _INTEGER_SCHEMA,
  CLOUDFLARE_TURNSTILE_SECRET: Joi.string().required(),
  CLOUDFLARE_ACCOUNT_ID: Joi.string().required(),
  CLOUDFLARE_R2_ACCESS_KEY: Joi.string().required(),
  CLOUDFLARE_R2_SECRET_KEY: Joi.string().required(),
  CLOUDFLARE_R2_BUCKET_NAME: Joi.string().required(),
  CLOUDFLARE_R2_ENDPOINT: Joi.string().required(),
  THROTTLE_TTL: _INTEGER_SCHEMA,
  THROTTLE_LIMIT: _INTEGER_SCHEMA,
  DB_HOST: _HOSTNAME_SCHEMA,
  DB_PORT: Joi.number().port().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  DB_URL: Joi.string().required(),
  REDIS_HOST: _HOSTNAME_SCHEMA,
  REDIS_PORT: Joi.number().port().required(),
  REDIS_PASSWORD: Joi.string().required(),
  REDIS_DB: Joi.number().integer().min(0).required(),
  REDIS_CACHE_TTL: _INTEGER_SCHEMA,
  REDIS_URL: Joi.string().required(),
  MAIL_API_KEY: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
})
